from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals


from rasa_nlu.training_data import load_data
from rasa_nlu.model import Trainer
from rasa_nlu import config
from rasa_nlu.model import Interpreter
import pprint
import datetime

# localtion of trained NLU model
model_location = 'projects/default/model_20180507-172620'

# location of training data
data_set = '/home/yifan/PycharmProjects/Chatito/data/rasa_training_20180507160002.json'


# Training NLU model
def test_train():
    print(datetime.datetime.now())
    # data_set generated by Chatito
    training_data = load_data(data_set)
    # load rasa pipeline
    trainer = Trainer(config.load("sample_configs/config_spacy.yml"))
    trainer.train(training_data)
    # save model
    trainer.persist('./projects/')
    print(datetime.datetime.now())


# Using trained NLU model to extract intents and entities from text
def test_prediction():
    # load model
    interpreter = Interpreter.load(model_location)
    # a simple console interface
    while True:
        var = input("[you]: ")
        response = interpreter.parse(var)
        pprint.pprint(response)


if __name__=='__main__':
    # test_train()
    test_prediction()
